name: Pre-release

on:
  push:
    tags:
      - "v*"

# Use "trusted publishing", see https://docs.pypi.org/trusted-publishers/
jobs:
  release:
    name: Publish pre-release Python distributions to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/schub
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: python -m pip install --upgrade pip wheel twine build
      - run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
